[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
itertools = "0.10.3"
rustc-hash = "1.1.0"
pathfinding = "3.0.5"
